version: "1.1"

services:
    tradingbot:
        build: .
        ports:
            - "1234:1234"
    #     links:
    #         - tradingbot_db

    # tradingbot_db:
    #     image: mysql:8
    #     restart: always
    #     ports: 
    #         - "3306:3306"
    #     environment: 
    #         - MYSQL_PASSWORD=douglas
    #         - MYSQL_DATABASE=tradingbot
    #         - MYSQL_USER=douglas
    #         - MYSQL_ROOT_PASSWORD=douglas
