version: "1.1"

services:
    tradingbot:
        build: .
        ports:
            - "1234:1234"
        depends_on:
            - mysql
            - redis
            - adapter
        container_name: tradingbot

    mysql:
        build: ./db/
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=fenske12
            - MYSQL_DATABASE=dockerproof
        container_name: tradingbot_db

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    celery:
        build: .
        command: sh -c "cd /app/service && celery -A celery_app worker --loglevel INFO"
        depends_on:
            - redis
            - tradingbot

    adapter:
        build: ./utils/
        ports: 
            - "8000:8000"
        container_name: adapter_nodejs

    front:
        build: ./front/
        ports:
            - "5173:5173"
        container_name: react_front


