name: Test

on: 
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - uses: actions/cache@v2
        id: cache-it
        with:
          path: |
            .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/Pipefile') }}
          restore-keys: |
            ${{ runner.os }}-venv

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install dependencies
        if: steps.cache-it.outputs.cache-hit != 'true'
        run: pipenv install --deploy --dev

#       - run: pipenv run pylint iqoptionapi
#       - run: pipenv run isort --recursive --diff .
#       - run: pipenv run black --check .
#       - run: pipenv run flake8
#       - run: pipenv run mypy
#       - run: pipenv run pytest --cov --cov-fail-under=100

